pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("com.gradle.develocity") version "4.4.2"
}

develocity {
    buildScan {
        termsOfUseUrl.set("https://gradle.com/help/legal-terms-of-use")
        termsOfUseAgree.set("yes")
    }
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = "ndk"
rootProject.buildFileName = "build.gradle.kts"

include(
    "sentry-native-ndk", "sample", "sentry-native-ndk-native"
)

// prefab uses the module name for determining the package name used by cmake find_package()
// thus rename the module to something better
project(':sentry-native-ndk').projectDir = new File("lib")
project(':sentry-native-ndk-native').projectDir = new File("native")
